compile: 
	arduino-cli compile --fqbn DFRobot:esp32:esp32 esp32-power-test.ino

upload: 
	arduino-cli upload -p /dev/cu.wchusbserial10 --fqbn DFRobot:esp32:esp32-e esp32-e-power-test.ino

send: 
	just compile
	just upload
